site_name: SOP4CWD
site_url: ''
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.footer
  custom_dir: docs/overrides
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - privacy
nav:
  - Home: index.md
  - About: about.md
  - CWD Data Warehouse:
    - warehouse/index.md
    - Data Collections: warehouse/data.md
    - Models: 
        - warehouse/models/index.md
        - Risk-weighted Surveillance Quotas Model: warehouse/models/RiskWeightedSurveillanceQuotasModel.md
        - Epizootic Risk Model:  warehouse/models/EpizooticRiskModel.md
        - Prevalence Estimator Data Export:  warehouse/models/PrevalenceEstimatorDataExport.md
        - Disease Cluster Analysis Data Export: warehouse/models/DiseaseClusterAnalysisDataExport.md
        - Sample Size for declaring freedom from disease in a clustered population: warehouse/models/FreedomFromDiseaseClusteredPopulation.md
        - In Development:
          - Disease Control Strategies Model: warehouse/models/DiseaseControlStrategiesModel.md
          - Home Range Contamination Model: warehouse/models/HomeRangeContaminationModel.md
    - Visualizations: warehouse/viz.md
    - Supporting documents: warehouse/warehouse-docs.md
  - Modeling Team: modeling.md
  - Research: research.md
  - Publications: publications.md
  - Partners: partners.md
  - Join SOP4CWD: join.md
  - Contact SOP4CWD: contact.md
markdown_extensions:
  - toc:
      permalink: false
      title: On this page
      toc_depth: 2
  - attr_list
  - tables
  - md_in_html      
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  generator: false
copyright: Copyright &copy; 2024 Cornell University