site_name: SOP4CWD
site_url: 'https://sop4cwd.org'
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.footer
  custom_dir: docs/overrides
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - privacy
nav:
  - Home: index.md
  - About: about.md
  - CWD Data Warehouse:
    - warehouse/index.md
    - Data Collections: warehouse/DataCollections.md
    - Models: 
        - warehouse/models/index.md
        - Risk-weighted Surveillance Quotas Model: warehouse/models/RiskWeightedSurveillanceQuotasModel.md
        - Sample Allocation Model: warehouse\models\SampleAllocationModel.md
        - Statistical Sample Quotas Using Clustering Model: warehouse/models/StatisticalSampleQuotas.md
        - Efficient Sample Size Calculator: warehouse/models/EfficientSampleSizeCalculator.md
        - Epizootic Risk Model: warehouse/models/EpizooticRiskModel.md
        - Simple Undetected Prevalence Estimator: warehouse\models\SimpleUndetectedPrevalenceEstimator.md
        - Prevalence Estimator Data Export: warehouse/models/PrevalenceEstimatorDataExport.md
        - Probability of Disease Freedom Using Clustering Model: warehouse/models/ProbabilityDiseaseFreedomClustering.md
        - Per-Sample Cost Analysis Model: warehouse\models\PerSampleCost.md
        - Positive Predictor Model: warehouse\models\PositivePredictorModel.md
        - Disease Cluster Analysis Data Export: warehouse\models/DiseaseClusterAnalysisDataExport.md
        - Outbreak Response Model: warehouse\models\OutbreakResponseModel.md
        - Disease Control Strategies Model: warehouse/models/DiseaseControlStrategiesModel.md
        - Home Range Contamination Model: warehouse/models/HomeRangeContaminationModel.md
        - Spread Model Data Export: warehouse\models\SpreadModelDataExport.md
        - Risk-weighted Surveillance Quotas Model (Western Expansion): warehouse/models/RiskWeightedSurveillanceQuotasModelWestern.md
        - Sample Allocation Model (Management Expansion): warehouse/models/SampleAllocationModelPartII.md
    - Visualizations: warehouse/Vizualizations.md
    - Supporting Documents: warehouse/SupportingDocuments.md
  - Facilitating Scientific Discovery: 
      - warehouse/team/index.md
      - Peruse SOP4CWD Publications: warehouse/team/Publications.md
      - Join the Quantitative Group: warehouse/team/QuantitativeGroup.md
      - Access Agency Data for Research: warehouse/team/DataRequests.md
      - Contribute a Model to the Warehouse: warehouse/team/ContributeModels.md
      - Learn from SOP4CWD Coordinators: warehouse/team/LearnFromUs.md
  - Project Partners: partners.md
  - Join SOP4CWD: join.md
  - Contact SOP4CWD: contact.md
markdown_extensions:
  - toc:
      permalink: false
      title: On this page
      toc_depth: 2
  - attr_list
  - tables
  - md_in_html      
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  generator: false
  CNAME: sop4cwd.org
copyright: Copyright &copy; 2024 Cornell University