site_name: SOP4CWD
site_url: 'https://sop4cwd.org'
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.footer
  custom_dir: docs/overrides
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - privacy
nav:
  - Home: index.md
  - About: about.md
  - CWD Data Warehouse:
    - warehouse/index.md
    - Data Collections: warehouse/data.md
    - Models: 
        - warehouse/models/index.md
        - Risk-weighted Surveillance Quotas Model: warehouse/models/RiskWeightedSurveillanceQuotasModel.md
        - Sample Size for Multiple Groups Model: warehouse/models/FreedomFromDiseaseClusteredPopulation.md
        - Statistical Sample Quotas using Clustering: warehouse/models/StatisticalSampleQuotas.md
        - Epizootic Risk Model: warehouse/models/EpizooticRiskModel.md
        - Prevalence Estimator Data Export: warehouse/models/PrevalenceEstimatorDataExport.md
        - Disease Cluster Analysis Data Export: warehouse\models/DiseaseClusterAnalysisDataExport.md
        - In Development:
          - Contact Structure Model: warehouse\models\ContactStructure.md
          - Disease Control Strategies Model: warehouse/models/DiseaseControlStrategiesModel.md
          - Home Range Contamination Model: warehouse/models/HomeRangeContaminationModel.md
          - Outbreak Response Tool: warehouse\models\OutbreakResponseTool.md
          - Positive Predictor Model: warehouse\models\PositivePredictorModel.md
          - Sample Allocation using Optimal Control Model: warehouse\models\SampleAllocationOptimalControl.md
          - Simple Prevalence Estimator: warehouse\models\SimplePrevalenceEstimator.md
          - Spread Model Data Export: warehouse\models\SpreadModelDataExport.md
          - Western Expansion of the Risk-weighted Surveillance Quotas Model: warehouse/models/RiskWeightedSurveillanceQuotasModelWestern.md
          - Expansion of the Sample Allocation Model to Surveillance, Prevention, and Management: warehouse/models/SampleAllocationOptimalControlPartII.md
    - Visualizations: warehouse/viz.md
    - Supporting documents: warehouse/warehouse-docs.md
  - Modeling Team: modeling.md
  - Research: research.md
  - Publications: publications.md
  - Partners: partners.md
  - Join SOP4CWD: join.md
  - Contact SOP4CWD: contact.md
markdown_extensions:
  - toc:
      permalink: false
      title: On this page
      toc_depth: 2
  - attr_list
  - tables
  - md_in_html      
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  generator: false
  CNAME: sop4cwd.org
copyright: Copyright &copy; 2024 Cornell University